name: Deploy snasirzadeh website

on:
  push:
    branches: ["master"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.HOST_PORT }} "cd ~/github/snasirzadeh-website && git status && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
