name: Deploy snasirzadeh website

on:
  push:
    branches: ["master"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure ssh config
      run: |
        bash -c "mkdir -p ~/.ssh/keys"
        bash -c "echo 'Host sepehr1' > ~/.ssh/config"
        bash -c "echo '    User debian' >> ~/.ssh/config"
        bash -c "echo '    Hostname ${{ secrets.HOST }}' >> ~/.ssh/config"
        bash -c "echo '    Port ${{ secrets.HOST_PORT }}' >> ~/.ssh/config"
        bash -c "echo '    IdentityFile ~/.ssh/keys/sepehr1' >> ~/.ssh/config"
        cat 
    - name: Add sepehr1 host key
      run: bash -c "echo test"
    - name: Configure ssh key
      run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/keys/sepehr1
          chmod 400 ~/.ssh/keys/sepehr1
          ssh sepehr1
          pwd
