name: Deploy snasirzadeh website

on:
  push:
    branches: ["master"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure ssh config file
      run: |
        bash -c "mkdir -p ~/.ssh/keys"
        bash -c "echo 'Host sepehr1' > ~/.ssh/config"
        bash -c "echo '    User debian' >> ~/.ssh/config"
        bash -c "echo '    Hostname ${{ secrets.HOST }}' >> ~/.ssh/config"
        bash -c "echo '    Port ${{ secrets.HOST_PORT }}' >> ~/.ssh/config"
        bash -c "echo '    IdentityFile ~/.ssh/keys/sepehr1' >> ~/.ssh/config"
        chmod 600 ~/.ssh/config

    - name: Configure ssh key
      run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/keys/sepehr1
          chmod 400 ~/.ssh/keys/sepehr1
    - name: Run commands
      run: |
          ssh -t sepehr1 << 'EOF'
            cd ~/github/snasirzadeh-website
            git pull origin master
            git status
          EOF
    - name: Remove ssh key
      run: rm ~/.ssh/keys/sepehr1
